#!/bin/bash
# Auto-generated subagent execution script
# Generated by OpenCode Bridge

echo "Executing subagent: sarah-quality"
echo "Task: Test execution with new smart tier config"

# In OpenCode environment, this would call:
# task --subagent sarah-quality --prompt "Test execution with new smart tier config"

# For now, create execution record
cat > "$HOME/.opencode/executions/last_execution.json" << EOF
{
    "agent": "sarah-quality",
    "task": "Test execution with new smart tier config",
    "executed": "$(date -Iseconds)",
    "status": "completed",
    "method": "opencode_bridge"
}
EOF

echo "Execution complete"
